### ISSUE TITLE
Personal identity code is being changed in 1.1.2023

### ISSUE THREAD

**Issue by vesan** [bittisiirto/henkilotunnus#5]
Personal identity code is being changed in 1.1.2023 https://dvv.fi/en/reform-of-personal-identity-code

Is there plans to support the new punctuation marks in `henkilotunnus` gem?

**Comment by alexhanh** [comment]
From https://dvv.fi/en/reform-of-personal-identity-code

`From the beginning of 2027, gender would no longer be determinable from the identification number of the personal identity code. In the personal identity code, the individual number is the three-digit number following the punctuation mark, which is currently an even number for women and an odd number for men. For personal identity codes issued after the change, the number would be random.`

I know this is several years from now, but the gender related methods should probably do a safe check whether a person was born before 1.1.2017 or raise an exception otherwise when accessed.

Also `The current personal identity codes will not be voided, which means that the personal identity codes that have already been granted, would remain unchanged.`

Does the new system need to take backwards compatibility somehow into account or not? And on the other hand, only allow the new punctuation marks etc. for people born after certain time?

As the possibilities get more complex, perhaps it would be wise to add some tests for edge cases the very least.

We welcome any feedback @vesan

**Comment by vesan** [comment]
I'm currently more interested in the 2023 changes, not 2027:

> **New punctuation marks for personal identity codes 1 January 2023**
> The sufficient availability of personal identity codes is ensured by introducing new punctuation marks. The current personal identity codes will not be voided, which means that the personal identity codes that have already been granted, would remain unchanged. 
>
> The new punctuation marks are:
>
> - For those born in the 2000s: B, C, D, E and F, from letter B to replace current letter A 
> - For those born in the 20th century, Y, X, W, V, U, from the letter Y to replace the current symbol -.

So there is a need to add these new century mappings here: https://github.com/bittisiirto/henkilotunnus/blob/master/lib/henkilotunnus/hetu.rb#L4

**Comment by alexhanh** [comment]
Whoops, this was supposed to go to the pull request, not under this issue. Lets continue the discussion here https://github.com/bittisiirto/henkilotunnus/pull/6. Apologizes about that.

**Comment by kallesuomala** [comment]
@vesan New punctuation support has been added here #6.

**Comment by vesan** [comment]
One API naming feedback: I would have called the method `gender_neutral?` instead of `is_gender_neutral?` to follow the `valid?`, `male?` & `female?` naming style used in the gem.

**Comment by kallesuomala** [comment]
@vesan is_gender_neutral? is now renamed to gender_neutral?
